es_host: 'search-demo-srlraiy5ym3njnndctzrk275du.us-west-2.es.amazonaws.com'
index_url: '/demo_index'
data_file: 'sample_data/demo1.csv'
mapping: 'sample_data/settings.json'
query_types:
  - 'sample_data/demo1.csv'
  - 'sample_data/demo2.csv'
